//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.1
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Qlasha.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Qlasha.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 10.
        /// </summary>
        internal static string CfgCrinkleCount {
            get {
                return ResourceManager.GetString("CfgCrinkleCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;HTML&gt;&lt;BODY&gt;OK&lt;/BODY&gt;&lt;/HTML&gt;.
        /// </summary>
        internal static string CfgHTMLEmpty {
            get {
                return ResourceManager.GetString("CfgHTMLEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;!DOCTYPE HTML PUBLIC &quot;-//W3C//DTD HTML 4.01//EN&quot; &quot;http://www.w3.org/TR/html4/strict.dtd&quot;&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        /// &lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=%encoding%&quot;&gt;
        /// &lt;title&gt;Qlasha&apos;s brain control panel&lt;/title&gt;
        ///&lt;/head&gt;
        ///
        ///&lt;body&gt;
        /// &lt;h1&gt;Qlasha&apos;s brain control panel&lt;/h1&gt;
        ///
        /// &lt;form method=Get action=&quot;/&quot;&gt;
        /// &lt;table&gt;
        ///  &lt;tr&gt;&lt;td&gt;Voice:&lt;/td&gt;
        ///  &lt;td&gt;%voice%&lt;/td&gt;&lt;/tr&gt;
        ///
        ///  &lt;tr&gt;&lt;td&gt;Rate (%rate%):&lt;/td&gt;
        ///  &lt;td&gt;&lt;SELECT NAME=&quot;rate&quot;&gt;
        ///   &lt;OPTION VALUE=&quot;-10&quot;&gt;-10&lt;/OPTION&gt;
        ///   &lt;OPTION VALUE=&quot;-9&quot;&gt;-9&lt;/OPTION&gt;
        /// [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string CfgHTMLFull {
            get {
                return ResourceManager.GetString("CfgHTMLFull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на +.
        /// </summary>
        internal static string CfgHTTPHosts {
            get {
                return ResourceManager.GetString("CfgHTTPHosts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 10160.
        /// </summary>
        internal static string CfgHTTPPort {
            get {
                return ResourceManager.GetString("CfgHTTPPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на http.
        /// </summary>
        internal static string CfgHTTPProtocol {
            get {
                return ResourceManager.GetString("CfgHTTPProtocol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 1.
        /// </summary>
        internal static string CfgOpacityNoTransparent {
            get {
                return ResourceManager.GetString("CfgOpacityNoTransparent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 0,3.
        /// </summary>
        internal static string CfgOpacityTransparent {
            get {
                return ResourceManager.GetString("CfgOpacityTransparent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на [^\w\d\s\.\,\?\!\&apos;\$\@\{\}_\&lt;\&gt;\&quot;\=\/\-].
        /// </summary>
        internal static string CfgRegExpNormalizeMessage {
            get {
                return ResourceManager.GetString("CfgRegExpNormalizeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ; .
        /// </summary>
        internal static string CfgSeparator {
            get {
                return ResourceManager.GetString("CfgSeparator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на -1.
        /// </summary>
        internal static string CfgSpeekRate {
            get {
                return ResourceManager.GetString("CfgSpeekRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 50.
        /// </summary>
        internal static string CfgSpeekVolume {
            get {
                return ResourceManager.GetString("CfgSpeekVolume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на encoding.
        /// </summary>
        internal static string CfgURLEncoding {
            get {
                return ResourceManager.GetString("CfgURLEncoding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на lastmessage.
        /// </summary>
        internal static string CfgURLLastMessage {
            get {
                return ResourceManager.GetString("CfgURLLastMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на message.
        /// </summary>
        internal static string CfgURLMessage {
            get {
                return ResourceManager.GetString("CfgURLMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на prefix.
        /// </summary>
        internal static string CfgURLPrefix {
            get {
                return ResourceManager.GetString("CfgURLPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на prefixes.
        /// </summary>
        internal static string CfgURLPrefixes {
            get {
                return ResourceManager.GetString("CfgURLPrefixes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на cp.
        /// </summary>
        internal static string CfgURLQueryCharset {
            get {
                return ResourceManager.GetString("CfgURLQueryCharset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на quiet.
        /// </summary>
        internal static string CfgURLQuiet {
            get {
                return ResourceManager.GetString("CfgURLQuiet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на rate.
        /// </summary>
        internal static string CfgURLRate {
            get {
                return ResourceManager.GetString("CfgURLRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на severity.
        /// </summary>
        internal static string CfgURLSeverity {
            get {
                return ResourceManager.GetString("CfgURLSeverity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на voice.
        /// </summary>
        internal static string CfgURLVoice {
            get {
                return ResourceManager.GetString("CfgURLVoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на volume.
        /// </summary>
        internal static string CfgURLVolume {
            get {
                return ResourceManager.GetString("CfgURLVolume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на RUS[Female] Alyona; RUS[Female] ScanSoft Katerina_Full_22kHz; RUS[Female];  RUS; [Female].
        /// </summary>
        internal static string CfgVoiceSelectAlg {
            get {
                return ResourceManager.GetString("CfgVoiceSelectAlg", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Dance {
            get {
                object obj = ResourceManager.GetObject("Dance", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Войти в мозг.
        /// </summary>
        internal static string MenuStrBrowser {
            get {
                return ResourceManager.GetString("MenuStrBrowser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выход.
        /// </summary>
        internal static string MenuStrExit {
            get {
                return ResourceManager.GetString("MenuStrExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Последнее сообщение.
        /// </summary>
        internal static string MenuStrLastMessage {
            get {
                return ResourceManager.GetString("MenuStrLastMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Скорость.
        /// </summary>
        internal static string MenuStrRate {
            get {
                return ResourceManager.GetString("MenuStrRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Голос.
        /// </summary>
        internal static string MenuStrVoice {
            get {
                return ResourceManager.GetString("MenuStrVoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Громкость.
        /// </summary>
        internal static string MenuStrVolume {
            get {
                return ResourceManager.GetString("MenuStrVolume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не могу я стать {0} потому что {1}; Не могу поменять голос на {0} потому что {1}.
        /// </summary>
        internal static string StrCantChangeVoice {
            get {
                return ResourceManager.GetString("StrCantChangeVoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на .
        /// </summary>
        internal static string StrEmpty {
            get {
                return ResourceManager.GetString("StrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не удается инициализировать подключение к мозгу по протоколу HTTP: {0}. Попробую еще раз;.
        /// </summary>
        internal static string StrErrorInitHTTP {
            get {
                return ResourceManager.GetString("StrErrorInitHTTP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0} сообщений я забыла...; а {0} сообщений я не скажу.
        /// </summary>
        internal static string StrForgetNMessages {
            get {
                return ResourceManager.GetString("StrForgetNMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Я говорила что {0}; Запоминай. {0}; Глухня! Я говорю что {0}; Ты что, меня не слышишь? Я сказала что {0}; Память тренеруй!; Уши прочисть!; Глухня!; Ты что меня не слушал?.
        /// </summary>
        internal static string StrLastMessage {
            get {
                return ResourceManager.GetString("StrLastMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на  и ;  а ещё ;  и ;  ну и ;  и ;  и кстати ;  и ; .
        /// </summary>
        internal static string StrMessageConnectors {
            get {
                return ResourceManager.GetString("StrMessageConnectors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отстань; Что тебе надо; Что хотел?; Отвали!; Не трогай меня!; Руки проч от советской власти!; Не трогай меня, я на работе; Отвали, ты себя в зеркало видел?.
        /// </summary>
        internal static string StrMouseDown {
            get {
                return ResourceManager.GetString("StrMouseDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Что смотришь?; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ;Не смотри на меня; ; ; ; ; ; ; ; ; ; ; ; ; ; ; .
        /// </summary>
        internal static string StrMouseHover {
            get {
                return ResourceManager.GetString("StrMouseHover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Куда; Отпусти!; Куда ты меня тащишь; Пусти меня; Куда ты меня повел, я не такая!.
        /// </summary>
        internal static string StrMouseMove {
            get {
                return ResourceManager.GetString("StrMouseMove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на дурак; ; ; ; ; ; ; идиот; ; ; ; ; ; ;.
        /// </summary>
        internal static string StrMouseUp {
            get {
                return ResourceManager.GetString("StrMouseUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;VOLUME LEVEL=&quot;100&quot;&gt;апчхи&lt;/VOLUME&gt;; ; ; ; ; ; ; ; ; ; ; &lt;VOLUME LEVEL=&quot;30&quot;&gt;фифифи&lt;/VOLUME&gt;; ; ; ; ; ; ; ; ; ; ; &lt;VOLUME LEVEL=&quot;30&quot;&gt;фифифифи&lt;/VOLUME&gt;; ; ; ; ; ; ; ; ; ; ; &lt;VOLUME LEVEL=&quot;30&quot;&gt;кхыкхы&lt;/VOLUME&gt;; ; ; ; ; ; ; ; ; ; ; &lt;VOLUME LEVEL=&quot;10&quot;&gt;хахаха&lt;/VOLUME&gt;; ; ; ; ; ; ; ; ; ; ; &lt;VOLUME LEVEL=&quot;10&quot;&gt;хыхыхы&lt;/VOLUME&gt;; ; ; ; ; ; ; ; ; ; ; &lt;VOLUME LEVEL=&quot;10&quot;&gt;хыхыхыхы&lt;/VOLUME&gt;; ; ; ; ; ; ; ; ; ; ;.
        /// </summary>
        internal static string StrOnTimer {
            get {
                return ResourceManager.GetString("StrOnTimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Скорость стала {0}; Я теперь говорю со скоростью {0}.
        /// </summary>
        internal static string StrRateChanged {
            get {
                return ResourceManager.GetString("StrRateChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Теперь я {0}; Я говорю голосом {0}; Мой голос поменялся на {0}.
        /// </summary>
        internal static string StrVoiceChanded {
            get {
                return ResourceManager.GetString("StrVoiceChanded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Громкость стала {0};Ты меня слышишь?; Как меня теперь слышно?.
        /// </summary>
        internal static string StrVolumeChanged {
            get {
                return ResourceManager.GetString("StrVolumeChanged", resourceCulture);
            }
        }
    }
}
